version: "3.7"

services:
  postgres:
    image: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=development
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  app:
    command: bundle exec rake db:migrate
    build:
      context: ./packages/migrator
    volumes:
      - ./packages/migrator:/app
      - bundle_path:/bundle
    depends_on:
      - postgres
    environment:
      - BUNDLE_PATH=/bundle/vendor
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=development
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_PORT=5432

volumes:
  bundle_path:
  postgres-data:
