name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  infra:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./packages/infra
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'yarn'
      - run: yarn install
      - run: yarn test

  migrator:
    runs-on: ubuntu-latest

    container: ruby:2.7

    defaults:
      run:
        working-directory: ./packages/migrator

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: development
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres

    steps:
      - uses: actions/checkout@v2
      - name: Postgres deps
        run: apt-get install -y postgresql-client
      - run: bundle install
      - name: Test migrations
        run: bundle exec rake db:migrate

